Kmenda w terminalu”
docker-compose up --build –d
error” 
33.31   Downloading pytz-2024.1-py2.py3-none-any.whl (505 kB)
0.0,>=3.4.0.0,<4.0.0.0
33.43 ERROR: Could not find a version that satisfies the requirement pywin32==306 (from versions: none)
33.43 ERROR: No matching distribution found for pywin32==306
33.65
33.65 [notice] A new release of pip is available: 23.0.1 -> 24.3.1
33.65 [notice] To update, run: pip install --upgrade pip
------
failed to solve: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
(.venv) PS C:\Project\myProject\DataScienceGroupProject\Marcinolo>
 W requairements.txt czeba umiwscic  ta linijke 
pywin32==306; platform_system == "Windows"  wtedy docker zignoruje pywin32==306
lub usunac z requariments.txt pywin32==306
nastepnie wpisz komende w terminalu aby przebudowac obraz w docker od nowa, ignorujac cache”
error”
40.10   Preparing metadata (pyproject.toml): finished with status 'error'
40.11   error: subprocess-exited-with-error
40.11
40.11   × Preparing metadata (pyproject.toml) did not run successfully.
40.11   │ exit code: 1
40.11   ╰─> [6 lines of output]
40.11
40.11       Cargo, the Rust package manager, is not installed or is not on PATH.
40.11       This package requires Rust and Cargo to compile extensions. Install it through     
40.11       the system's package manager or via https://rustup.rs/
40.11
40.11       Checking for Rust toolchain....
40.11       [end of output]
40.11
40.11   note: This error originates from a subprocess, and is likely not a problem with pip.   
40.12 error: metadata-generation-failed
40.12
40.12 × Encountered error while generating package metadata.
40.12 ╰─> See above for output.
40.12
40.12 note: This is an issue with the package mentioned above, not pip.
40.12 hint: See above for details.
40.31
40.31 [notice] A new release of pip is available: 23.0.1 -> 24.3.1
40.31 [notice] To update, run: pip install --upgrade pip
------
failed to solve: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1

ponownie uruchom docker komenda 
docker-compose up –d

error “
31.64   error: subprocess-exited-with-error
31.64
31.64   × Preparing metadata (pyproject.toml) did not run successfully.
31.64   │ exit code: 1
31.64   ╰─> [6 lines of output]
31.64
31.64       Cargo, the Rust package manager, is not installed or is not on PATH.
31.64       This package requires Rust and Cargo to compile extensions. Install it through     
31.64       the system's package manager or via https://rustup.rs/
31.64
31.64       Checking for Rust toolchain....
31.64       [end of output]
31.64
31.64   note: This error originates from a subprocess, and is likely not a problem with pip.   
31.65 error: metadata-generation-failed
31.65
31.65 × Encountered error while generating package metadata.
31.65 ╰─> See above for output.
31.65
31.65 note: This is an issue with the package mentioned above, not pip.
31.65 hint: See above for details.
31.88
31.88 [notice] A new release of pip is available: 23.0.1 -> 24.3.1
31.88 [notice] To update, run: pip install --upgrade pip
------
failed to solve: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
(.venv) PS C:\Project\myProject\DataScienceGroupProject\Marcinolo>

błąd wskazuje, że jedna z paczek w requirements.txt wymaga kompilacji rozszerzeń w Rust, co wymaga zainstalowania narzędzi Rust i Cargo. Docker nie posiada tych narzędzi domyślnie, więc musimy je dodać do obrazu.

W tym momencie postanowilem wrzucic tylko wymagane biblioteki oto one”
fastapi==0.115.4
uvicorn==0.22.0
joblib==1.4.2
numpy==1.26.4
pandas==2.2.2
jinja2==3.1.2
python-multipart==0.0.5
scikit-learn==1.5.2

I po wpisaniu komendy docker-compose up –d
Docker odpalil oto wynik”
(.venv) PS C:\Project\myProject\DataScienceGroupProject\Marcinolo> docker-compose up -d        
time="2024-11-08T20:48:25-05:00" level=warning msg="C:\\Project\\myProject\\DataScienceGroupProject\\Marcinolo\\docker-compose.yml: `version` is obsolete"
[+] Building 48.6s (9/9) FINISHED                                         docker:desktop-linux 
 => [app internal] load build definition from Dockerfile                                  0.0s 
 => => transferring dockerfile: 472B                                                      0.0s 
 => [app internal] load metadata for docker.io/library/python:3.10-slim                   0.6s 
 => [app internal] load .dockerignore                                                     0.0s 
 => => transferring context: 2B                                                           0.0s 
 => [app 1/4] FROM docker.io/library/python:3.10-slim@sha256:eb9ca77b1a0ffbde84c1dc333be  0.0s 
 => [app internal] load build context                                                     0.1s 
 => => transferring context: 3.70kB                                                       0.0s 
 => CACHED [app 2/4] WORKDIR /app                                                         0.0s 
 => [app 3/4] COPY . /app                                                                 0.5s 
 => [app 4/4] RUN pip install --no-cache-dir -r requirements.txt                         43.8s 
 => [app] exporting to image                                                              3.2s
 => => exporting layers                                                                   3.1s
 => => writing image sha256:0c854fb5c1814e38a5a8dfed7acb380c0d4c65beccb3a323c525229d39c1  0.0s 
 => => naming to docker.io/library/marcinolo-app                                          0.0s 
[+] Running 1/1
 ✔ Network marcinolo_default  Created                                                     0.1s 
 - Container fastapi_app      Creating                                                    0.0s 
Error response from daemon: Conflict. The container name "/fastapi_app" is already in use by container "696e7bcc79136f600cce443b8dcf390adefe6f69dbf68cf6423a809ddbfd9eb0". You have to remove 
(or rename) that container to be able to reuse that name.
(.venv) PS C:\Project\myProject\DataScienceGroupProject\Marcinolo>

W tym momencie musisz usunac  kontener by ten nowo utworzony dzialal” lub zmienic nazwe kontenera.Lub w docker_compose.yml wpisac nowa nazwe jak ponizejw tym miejscu”

services:
  app:
    container_name: fastapi_app_new  # Zmieniona nazwa
    ...
Jezeli otrzymasz taki blad „
(.venv) PS C:\Project\myProject\DataScienceGroupProject\Marcinolo> docker rm -f fastapi_app    
Error response from daemon: No such container: fastapi_app

Sprawdz komenda 
docker ps –a

To polecenie pokaże pełną listę kontenerów. Jeśli zobaczysz kontener o nazwie /fastapi_app lub podobnej, zanotuj jego ID (zwykle będzie to ciąg znaków rozpoczynający się od cyfr i liter) i usuń go za pomocą:
docker rm -f <ID_kontenera>

jezeli nie posiadasz fastapi a error ten masz to możesz spróbować uruchomić docker-compose up w trybie bez bufora, aby upewnić się, że nie ma problemów z cache:
docker-compose up --force-recreate –d

oto wynik “
(.venv) PS C:\Project\myProject\DataScienceGroupProject\Marcinolo> docker-compose up --force-recreate -d
time="2024-11-08T21:06:26-05:00" level=warning msg="C:\\Project\\myProject\\DataScienceGroupProject\\Marcinolo\\docker-compose.yml: `version` is obsolete"
[+] Running 1/1
 ✔ Container fastapi_app  Started                                                         1

Nastepnie uzyj komendy w terminal “
docker-compose up –d

wynik 
(.venv) PS C:\Project\myProject\DataScienceGroupProject\Marcinolo> docker-compose up -d    
time="2024-11-08T21:07:49-05:00" level=warning msg="C:\\Project\\myProject\\DataScienceGroupProject\\Marcinolo\\docker-compose.yml: `version` is obsolete"
[+] Running 1/0
 ✔ Container fastapi_app  Running                                               

Wpisz komende „
docker build -t fastapi_app .

wynik”
(.venv) PS C:\Project\myProject\DataScienceGroupProject\Marcinolo> docker build -t fastapi_app 
.
[+] Building 44.5s (9/9) FINISHED                                         docker:desktop-linux 
 => [internal] load build definition from Dockerfile                                      0.0s 
 => => transferring dockerfile: 472B                                                      0.0s 
 => [internal] load metadata for docker.io/library/python:3.10-slim                       0.7s 
 => [internal] load .dockerignore                                                         0.0s 
 => => transferring context: 2B                                                           0.0s 
 => [1/4] FROM docker.io/library/python:3.10-slim@sha256:eb9ca77b1a0ffbde84c1dc333beb349  0.0s 
 => [internal] load build context                                                         0.0s 
 => => transferring context: 2.75kB                                                       0.0s 
 => CACHED [2/4] WORKDIR /app                                                             0.0s 
 => [4/4] RUN pip install --no-cache-dir -r requirements.txt                             39.5s 
 => exporting to image                                                                    3.1s 
 => => exporting layers                                                                   3.0s 
 => => writing image sha256:af7319aa28dba2fadc812ae62707b99378b110a19f57e57eddfac83da11d  0.0s 
 => => naming to docker.io/library/fastapi_app                                            0.0s 

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/mq3yb87dkra7nhghys54hy20k

What's next:
    View a summary of image vulnerabilities and recommendations → docker scout quickview  

Jezeli po wpisaniu komendy “
docker run -d -p 8000:8000 fastapi_app  

otrzymasz error”
(.venv) PS C:\Project\myProject\DataScienceGroupProject\Marcinolo> docker run -d -p 8000:8000 fastapi_app
575dbf6030d066d863ae6b5630d5eaefff26c9f7116eafeacb74ceb029f1d5ff
docker: Error response from daemon: driver failed programming external connectivity on endpoint sweet_chandrasekhar (42f091270a7b82c42b7f34ff4d6dc4869d9bbc6e7fd01817e14f5d01e7a71e9e): Bind for 0.0.0.0:8000 failed: port is already allocated.

sprawdz czy contener fastapi dziala juz ,komenda”
docker ps

wynik powinien wygladac tak”
(.venv) PS C:\Project\myProject\DataScienceGroupProject\Marcinolo> docker ps
CONTAINER ID   IMAGE           COMMAND                  CREATED         STATUS         PORTS   
                           NAMES
a145581f8219   marcinolo-app   "uvicorn main:app --…"   6 minutes ago   Up 5 minutes   0.0.0.0:8000->8000/tcp, 8080/tcp   fastapi_app

nastepnie musisz zatrzymac dany kontener fastapi komenda”
docker stop fastapi_app

nastepnie uruchom ponownie aplikacje
docker run -d -p 8000:8000 fastapi_app

wynik"
(.venv) PS C:\Project\myProject\DataScienceGroupProject\Marcinolo> docker run -d -p 8000:8000 fastapi_app
6a8e757f580c2d354583620a5ac8bcc2e5418370c901b24d216b22fb5bdf1e6e

To sa poszczegolne kroki przy errorach jakie masz lub miales po odpalaniu docker run -d -p 8000:8000 fastapi_app.
 
Jezeli chodzi o main.py u ciebie brakuje 

import os
oraz 
# Wczytanie zmiennych środowiskowych
MODEL_PATH = os.getenv("MODEL_PATH", "model_random_forest.pkl")
PORT = int(os.getenv("PORT", 8000))
DEBUG = os.getenv("DEBUG", "True").lower() in ("true", "1")

Ktore wpisujesz po bibliotekach 

Jezeli ponownie po uruchomieniou masz ten blad “
- Container fastapi_app  Starting                                                        0.5s 
Error response from daemon: driver failed programming external connectivity on endpoint fastapi_app (181138dc77752ce3e978d28e961255114195c3ea4da3194c51d1f5f2438d9a5e): Bind for 0.0.0.0:8000 
failed: port is already allocated
zatrzymaj  i usun istniejace kontenery w moich poprzednich zadaniach domowych na dockerze usuwalem wszystkie kontenery i na nowo robilem nowe jak i rownierz obrazy tak ze mialem dockera czystego.
 Lub w docker_compose.yml zmien port na 8001 jak ponizej 
 ports:
      - "8001:8000"
 Ja otrzymalem taki wynik 
(.venv) PS C:\Project\myProject\DataScienceGroupProject\Marcinolo> docker-compose up --build -d

time="2024-11-08T21:35:11-05:00" level=warning msg="C:\\Project\\myProject\\DataScienceGroupProject\\Marcinolo\\docker-compose.yml: `version` is obsolete"
[+] Building 39.6s (9/9) FINISHED                                         docker:desktop-linux
 => [app internal] load build definition from Dockerfile                                  0.0s
 => => transferring dockerfile: 472B                                                      0.0s 
 => [app internal] load metadata for docker.io/library/python:3.10-slim                   0.4s 
 => [app internal] load .dockerignore                                                     0.0s 
 => => transferring context: 2B                                                           0.0s 
 => [app 1/4] FROM docker.io/library/python:3.10-slim@sha256:eb9ca77b1a0ffbde84c1dc333be  0.0s 
 => [app internal] load build context                                                     0.0s 
 => => transferring context: 3.46kB                                                       0.0s 
 => CACHED [app 2/4] WORKDIR /app                                                         0.0s 
 => [app 3/4] COPY . /app                                                                 1.1s 
 => [app 4/4] RUN pip install --no-cache-dir -r requirements.txt                         34.8s 
 => [app] exporting to image                                                              3.0s
 => => exporting layers                                                                   3.0s
 => => writing image sha256:144d8dc3a6ab9f044080d945a0983951d1dbb505fb36a19d3e91d726f5ac  0.0s 
 => => naming to docker.io/library/marcinolo-app                                          0.0s 
[+] Running 1/1
 ✔ Container fastapi_app  Started                                                         0.8s 
(.venv) PS C:\Project\myProject\DataScienceGroupProject\Marcinolo>
Nastepnie scopiuj I wklej link do przegladarki “
http://localhost:8000/form
 i otworzy sie stronka naszego formularza   
